### ISSUE TITLE
Load icons faster

### ISSUE THREAD

**Issue by duckness** [duckness/Mask-of-Goblin#11]
Maybe precache all the icons after initial load.

![](https://user-images.githubusercontent.com/6380270/32385397-ec9f4504-c0f8-11e7-8a3c-dbeea894c5f8.gif)

**Comment by ferrerojosh** [comment]
You can use [vue-clazy-load](https://github.com/matheusgrieger/vue-clazy-load) add a css3 spinner on it while it loads

**Comment by duckness** [comment]
images are now lazy loaded
