### ISSUE TITLE
a minor issue in calculator (atk spd)

### ISSUE THREAD

**Issue by Ano12345** [duckness/Mask-of-Goblin#12]
just noticed a minor issue seem if the atk speed set to 1751 it has lower % (174.9%) than 1750 (175%)
![image](https://user-images.githubusercontent.com/35865833/35471132-fb9990e2-0387-11e8-962d-1de2bfcc989f.png)

**Comment by duckness** [comment]
it's just the way the formula works, you can see the "problem" anytime you are 1 above a softcap value. Since all things in the game are at least an increment of 5, this is not a problem.

**Comment by Ano12345** [comment]
I see thanks. Just maybe something amiss.
