### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by duckness** [duckness/Mask-of-Goblin#14]
You can preview the new site [here](https://rewrite.maskofgoblin.com/).

Known outstanding issues:

- [x]  All issues with i18n
  - [x] Automatically generate variable data
  - [x] Automatically generate UI Strings
  - [x] Get all translations
- [x]  Routing to each of the artifacts & heroes
- [x]  Calculator is missing
- [x] Missing images for newer heroes

---------
Food for thought (after rewrite merge to master?):
- Revamp site design
- Update dep (font-awesome)
- Automatically parse more difficult to parse data (AA cycles, etc)
- Somehow explain some of the more complex stuff in the data on the site
- Tagging system with search? (e.g. `mamp`, `mshred`)

**Comment by ferrerojosh** [comment]
Offline support ? Well this can be done later

**Comment by duckness** [comment]
If the browser requests Chinese and no preference is given by the browser, the site will give Chinese Simplified.

If there are any valid objections please create a new issue.
