### ISSUE TITLE
No update anymore?

### ISSUE THREAD

**Issue by Phobophile** [duckness/Mask-of-Goblin#15]
I am a mask user. You provided a lot of useful hidden info and helped me a lot. But there seems no update since 1 month ago and the skill info of last three heroes are not complete. So you quit KR or these data cannot be easily mined anymore? Sincerely thanks for your work.

**Comment by duckness** [comment]
The current version just takes too much time to update and I've been lazy. I've been trying to automate some things but I've been lazy on that too.

**Comment by duckness** [comment]
All datamined. Unfortunately I will not be answering questions on how to do that.

**Comment by Phobophile** [comment]
It's a pity to hear that. Thanks for your response.

**Comment by duckness** [comment]
Actually updating the site
