### ISSUE TITLE
How do  yo get the detail formula?

### ISSUE THREAD

**Issue by polarbear127** [duckness/Mask-of-Goblin#16]
Hi mate.

Thanks for your works! However, it looks discontinued, doesn't it? Could you tell me how did you get the exact formula for this calculator?
Since 6/14 update, there have been some parameters changed. I would like to fork this project and change the latest settings, for example, Vespa set atk speed softcap from 1750 decreased to 1600.

**Comment by duckness** [comment]
I'll fix the calculator soon.
